### ISSUE TITLE
Possible deadlock?

### ISSUE THREAD

**Issue by dpsutton** [hiredman/queue#1]
This form consistently seems to deadlock for me

```clojure
(comment

  (let [threads 2
        items   (long (* 6 1e4))]
    (let [q (java.util.concurrent.LinkedBlockingQueue.)
          done (java.util.concurrent.CountDownLatch. threads)]
      (time (do (doseq [_ (range threads)]
                  (.start (Thread. (fn []
                                     (doseq [i (range items)]
                                       (.add q i))
                                     (.countDown done)))))
                (.await done))))
    (let [q (queue)
          done (java.util.concurrent.CountDownLatch. threads)]
      (time (do (doseq [_ (range threads)]
                  (.start (Thread. (fn []
                                     (doseq [i (range items)]
                                       (enqueue q i))
                                     (.countDown done)))))
                (.await done)))))
  )
```

If `items` is `(long (* 5 1e4))` it works just fine. 

I think its compare and set dance between two threads that keep invalidating the compares. Not sure if this is used in production but just reading through and was benchmarking.

**Comment by hiredman** [comment]
I am unable to reproduce this. At around 1e8 it starts to take a *really* long time to run on my laptop, I haven't actually seen linkedblockingqueue finish at 1e8.

**Comment by dpsutton** [comment]
are you checking without the patch from https://github.com/hiredman/queue/pull/2 ? That PR rectified this i believe.

**Comment by dpsutton** [comment]
I believe this can be closed. i checked again and the PR has fixed it.
